POST http://localhost:8080/user/signup
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "email" : "cdon@gmail.com",
    "password" : "tochi12345"
}

###

POST http://localhost:8080/user/login
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "password" : "tochi12345"
}

###
GET http://localhost:8081/user/getAll
Content-Type: application/json

###

POST http://localhost:8081/user/editUser
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf2",
    "username" : "Tochi Edit",
    "password" : "dwwrwr"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf1"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "634edb2a16710b2cda6fb370"
}

###
POST  http://localhost:8081/user/deleteAll
###

//ITEMS

GET http://localhost:8081/item/getAll
Content-Type: application/json

###
POST http://localhost:8081/item/createNewItem
Content-Type: application/json 

{
    "id" : "_salad_",
    "name" : "House Salad",
    "price" : 11.00
}

###
GET http://localhost:8081/item/getItemById/_salad_ HTTP/1.1
Content-Type: application/json

###
GET  http://localhost:8081/item/getItemByDBId/6426dd96ce3ef0237ff01b48
Content-Type: application/json 

###
DELETE http://localhost:8081/item/deleteItemById/6418fd4a6109200daaac192f
Content-Type: application/json

###

DELETE http://localhost:8081/item/deleteAll HTTP/1.1
Content-Type: application/json

{
}

###

PUT http://localhost:8081/item/editItem/6426d6c7ce3ef0237ff01b14 
Content-Type: application/json
{
  "id": "_salad_",
  "name": "Ceaser Salad",
  "price": 15

}

###
//TICKETS
POST http://localhost:8081/ticket/createNew
Content-Type: application/json
{
    "serverName": "John Doe",
  "items" : ["Item 5", "Item 2", "Item 4"],
  "totalSum" : 120
}

###
GET http://localhost:8081/ticket/getAll
Content-Type: application/json
###

DELETE http://localhost:8081/ticket/deleteTicketById/6426ebe1b6de4b0fd3bdb317
Content-Type: application/json

###

DELETE http://localhost:8081/ticket/deleteAll
Content-Type: application/json

###
PUT http://localhost:8081/ticket/editTicket/6426fc1f72a2764e22c001aa
Content-Type: application/json
{
    "items":
    [
        "item 6",
        "new 4"
    ]
}
###

